export const categorySections = [
    { id: 1, name: 'Acessórios', value: 'accessories' },
    { id: 2, name: '⁠Calçados', value: 'footwear' },
    { id: 3, name: 'Moda Praia', value: 'beachFashion' },
    { id: 4, name: '⁠Peças Inferiores', value: 'bottom' },
    { id: 5, name: 'Peças Superiores', value: 'top' },
    { id: 6, name: 'Peças Únicas (macacão, vestido, jardineira)', value: 'fullbody' },
    { id: 7, name: 'Peças de Sobreposição (agasalhos, jaquetas)', value: 'outerwear' },
    { id: 8, name: 'Roupas Esportivas', value: 'sportswear' },
];

export const estados = [
    { id: 1, label: 'Acre', value: 'AC' },
    { id: 2, label: 'Alagoas', value: 'AL' },
    { id: 3, label: 'Amapá', value: 'AP' },
    { id: 4, label: 'Amazonas', value: 'AM' },
    { id: 5, label: 'Bahia', value: 'BA' },
    { id: 6, label: 'Ceará', value: 'CE' },
    { id: 7, label: 'Distrito Federal', value: 'DF' },
    { id: 8, label: 'Espírito Santo', value: 'ES' },
    { id: 9, label: 'Goiás', value: 'GO' },
    { id: 10, label: 'Maranhão', value: 'MA' },
    { id: 11, label: 'Mato Grosso', value: 'MT' },
    { id: 12, label: 'Mato Grosso do Sul', value: 'MS' },
    { id: 13, label: 'Minas Gerais', value: 'MG' },
    { id: 14, label: 'Pará', value: 'PA' },
    { id: 15, label: 'Paraíba', value: 'PB' },
    { id: 16, label: 'Paraná', value: 'PR' },
    { id: 17, label: 'Pernambuco', value: 'PE' },
    { id: 19, label: 'Piauí', value: 'PI' },
    { id: 20, label: 'Rio de Janeiro', value: 'RJ' },
    { id: 21, label: 'Rio Grande do Norte', value: 'RN' },
    { id: 22, label: 'Rio Grande do Sul', value: 'RS' },
    { id: 23, label: 'Rondônia', value: 'RO' },
    { id: 24, label: 'Roraima', value: 'RR' },
    { id: 25, label: 'Santa Catarina', value: 'SC' },
    { id: 26, label: 'São Paulo', value: 'SP' },
    { id: 28, label: 'Sergipe', value: 'SE' },
    { id: 29, label: 'Tocantins', value: 'TO' }
];